name: Link health
on:
  schedule: [{ cron: "0 */4 * * *" }]
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --config lychee.toml
            .
